version: '3'
services:
    dynamodb:
      build: ./
      command: -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -dbPath "/home/dynamodblocal/dynamodb-storage" -sharedDb
      ports:
        - "8000:8000"
      volumes:
        - "$PWD/testdata/dynamodb-storage:/home/dynamodblocal/dynamodb-storage"
